server:
  port: 8080
spring:
  application:
    name: Whatwapp gateway
  jpa:
    hibernate:
      ddl-auto: create-drop
      default_schema: schema
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console